markdown: kramdown
highlighter: rouge
permalink: "/posts/:title/"

name: "Jonathan Palardy"
blog_name: "Jonathan Palardy's Blog"
url: "https://blog.jpalardy.com"
description: "Jonathan Palardy's blog about technology"
email: "jonathan.palardy@gmail.com"
bluesky_username: "jpalardy.bsky.social"
github_username: "jpalardy"
gravatar_url: "https://www.gravatar.com/avatar/ecfd1bdc5d3aab1e40f25658817712ba"
