markdown: rdiscount
highlighter: pygments
permalink: "/posts/:title/"
rdiscount:
  extensions: [smart]

name: "Jonathan Palardy"
blog_name: "Jonathan Palardy's Blog"
url: "http://blog.jpalardy.com"
description: "Jonathan Palardy's blog about technology"
email: "jonathan.palardy@gmail.com"
twitter_username: "jpalardy"
github_username: "jpalardy"
gravatar_url: "http://www.gravatar.com/avatar/ecfd1bdc5d3aab1e40f25658817712ba"
